### PR TITLE
Running in parallel using testng.xml file

### PR DESCRIPTION
**Pull request by ndmanvar**

### CODE REVIEW

**Comment by ndmanvar** [comment]
@mehmetg @KevinMarkVI Could you please review?

**Comment by ndmanvar** [comment]
Tested this out and it spins up 20 threads.
4 test cases (2 in each file) x 5 browsers = 20 tests running in sauce in parallel.

**Comment by KevinMarkVI** [comment]
Thumbs Up

**Comment by ndmanvar** [comment]
@mehmetg Could you please review?

**Comment by mehmetg** [comment]
It looks great, but are you sure about the 50 thread limit? The recommendation is # cores * 1.5. Are there any other considerations for setting it as high?

If the thread count is intentional :+1:

**Pull request closed without merging**
